version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'crmdb'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'appdomain!'
       MYSQL_ROOT_PASSWORD: 'appdomain!'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/simplecrm
    ports:
      - "8000:8000"
    depends_on:
      - db